name: simple
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.3
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  json_annotation: ^4.7.0
  orm: ^2.4.0
