name: simple
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  lints: ^2.0.1
  test: ^1.22.1

dependencies:
  json_annotation: ^4.7.0
  orm: ^2.4.6
