name: orm
description: â—­ Next-generation ORM for Dart & Flutter | PostgreSQL, MySQL, MariaDB, SQL Server, SQLite, MongoDB and CockroachDB.
version: 3.4.7
homepage: https://prisma.pub
repository: https://github.com/medz/prisma-dart
funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  prisma: orm

dependencies:
  # Library dependencies
  crypto: ^3.0.3
  http: ^1.0.0
  json_annotation: ^4.8.1
  meta: ^1.9.1
  path: ^1.8.3
  retry: ^3.1.2

  # CLI dependencies
  analyzer: '>=5.13.0 <7.0.0'
  code_builder: ^4.4.0
  dart_style: ^2.3.1
  recase: ^4.1.0
  freezed_annotation: ^2.4.1
  json_rpc_2: ^3.0.2
  stream_channel: ^2.1.2

# Devlopment dependencies
dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.4.5
  json_serializable: ^6.7.0
  lints: ^2.1.0
  test: ^1.24.3
