name: orm
description: â—­ Next-generation ORM for Dart & Flutter | PostgreSQL, MySQL, MariaDB, SQL Server, SQLite, MongoDB and CockroachDB.
version: 2.4.3
homepage: https://prisma.pub
repository: https://github.com/odroe/prisma-dart
funding:
  - https://opencollective.com/prisma-dart
  - https://opencollective.com/odroe

environment:
  sdk: '>=2.18.0 <3.0.0'

executables:
  prisma: orm

dependencies:
  archive: ^3.3.1
  args: ^2.3.1
  code_builder: ^4.3.0
  crypto: ^3.0.2
  dart_style: ^2.2.3
  http: ^0.13.5
  json_annotation: ^4.6.0
  path: ^1.8.2
  rc: ^0.2.2
  retry: ^3.1.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.21.6
