name: orm_example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  orm: any

dependency_overrides:
  orm:
    path: ../orm
