name: orm
description: Next-generation ORM for Dart & Flutter | PostgreSQL, MySQL, MariaDB, SQL Server, SQLite, MongoDB and CockroachDB.
homepage: https://prisma.pub
repository: https://github.com/medz/prisma-dart

resolution: workspace
version: 5.3.3

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

topics:
  - orm
  - prisma
  - database

environment:
  sdk: ^3.5.0

executables:
  prisma-client-dart: orm

dependencies:
  code_builder: ^4.10.0
  dart_style: ^2.3.7 # TODO: await ffigen update the dep
  decimal: ^3.1.0
  json_rpc_2: ^3.0.2
  path: ^1.9.0
  rc: ^0.3.3
  recase: ^4.1.0
  stream_channel: ^2.1.2
  webfetch: ^0.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.8
