name: orm
description: Next-generation ORM for Dart & Flutter | PostgreSQL, MySQL, MariaDB, SQL Server, SQLite, MongoDB and CockroachDB.
version: 5.1.0
homepage: https://prisma.pub
repository: https://github.com/medz/prisma-dart
funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

topics:
  - orm
  - prisma
  - database
  - db

environment:
  sdk: ^3.4.0

executables:
  prisma-client-dart: orm

dependencies:
  code_builder: ^4.8.0
  dart_style: ^2.3.4
  decimal: ^3.0.0
  json_rpc_2: ^3.0.2
  path: ^1.8.3
  rc: ^0.3.3
  recase: ^4.1.0
  stream_channel: ^2.1.2
  webfetch: ^0.0.17

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.8
