name: orm_flutter
description: "The engine of Prisma ORM for Flutter, Library for binding Prisma's C-Abi engine with Flutter."
homepage: https://prisma.pub
repository: https://github.com/medz/prisma-dart

resolution: workspace
version: 0.5.1

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

environment:
  sdk: ^3.5.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  orm: ^5.2.1
  orm_flutter_ffi: ^0.0.3

dev_dependencies:
  flutter_lints: ^6.0.0
