name: with_sqlite
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  orm:
    path: ../../packages/orm

dev_dependencies:
  lints: ^3.0.0
