name: prisma_dart_docs_example
description: Prisma Dart Client Example
version: 1.0.0
publish_to: "none"
resolution: workspace
repository: https://github.com/medz/prisma-dart
homepage: https://github.com/medz/prisma-dart/tree/master/example

environment:
  sdk: ^3.5.0

dependencies:
  orm:
    path: ../packages/orm

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.8
