name: prisma_get_platform
description: Prisma ORM for Dart Gets the platform names supported by the Prisma binary engines.
version: 0.0.1
homepage: https://prisma.pub
repository: https://github.com/odroe/prisma-dart

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
