name: prisma_with_postgres
description: A sample command-line application.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  orm:
    path: ../../packages/orm

dev_dependencies:
  lints: ^5.0.0
