name: Publish

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    tags: ["orm-v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  publish:
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
